name: test-deploy-nuxt.js
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/test-deploy-nuxt.js
  name: test-deploy-nuxt.js
